### ISSUE TITLE
commands.extフレームワークは使用しないのか

### ISSUE THREAD

**Issue by sizumita** [Alpaca131/discord-typing#1]
https://github.com/Alpaca131/discord-typing/blob/95a31238904c6899efe2ebcf1301b6adb2b130e0/bot.py#L31-L105

こちらでon_messageの中でコマンドを作っていますが、これからも増えていくと考えると、すでに70行になっており分割するかcommands.extフレームワークを使用した方がいいと思います。

**Comment by Alpaca131** [comment]
使う予定です。そのうち書き直します。ありがとうございます。

**Comment by Alpaca131** [comment]
pycordを使用してスラッシュコマンドでの書き直しを始めることに

**Comment by Alpaca131** [comment]
#3
