### ISSUE TITLE
GameInfoの命名が不適切

### ISSUE THREAD

**Issue by daima3629** [Alpaca131/discord-typing#7]
https://github.com/Alpaca131/discord-typing/blob/ba0fcd24767b5a18e60315189ef3c31223dd3c13/classes/game_class.py#L18
Infoという名前はデータクラスを連想させるものであるが、実態はゲームプロセスを管理するクラスであるため、`Game` や `GameManager` などの命名が適切

**Comment by Alpaca131** [comment]
これ見る前にGameObjにリネームしちゃったんだけどこれはどう？

**Comment by Alpaca131** [comment]
Managerだと保存関係の関数があるgames_funcと命名的に被る気がして

**Comment by Alpaca131** [comment]
こちらの[コミット](https://github.com/Alpaca131/discord-typing/pull/3/commits/d21bc98999bfa51ac7c5afba9a5fc5ecaf84f1d3)でこの案を採用
